


[.bc: ../coreutils_source/ ../coreutils_source/coreutils/src/[
	cp ../coreutils_source/coreutils/src/[ .
	get-bc [


../coreutils_source/:
	make -C ../

../coreutils_source/coreutils/src/[:
	make -C ../coreutils_source/coreutils/ -j4

clean:
	rm -rf *.bc [ slash *_slashed *log
